lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    # token extraction settings
    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

        # check token in a cookie
        #cookie:
        #    enabled: true
        #    name: BEARER

    # Automatically generating cookies:
    #https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#automatically-generating-cookies
    #set_cookies:
    #    BEARER: ~
            #lifetime: null #defaults to token ttl
            #samesite: lax
            #path: /
            #domain: null #null means automatically set by symfony    