security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md#configuring-the-user-provider
        jwt:
            lexik_jwt:
                class: App\Security\User
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            # allow authentication using a form or HTTP basic
            pattern: ^/login
            stateless: true
            provider: app_user_provider
            json_login:
                # The check_path can also be a route name (but cannot have mandatory wildcards - e.g. /login/{foo}
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # put it before all your other firewall API entries
        refresh:
            pattern: ^/token/refresh
            stateless: true
            security: false # Symfony 6 design -> anonymous: true not valid anymore!

        api:
            stateless: true
            provider: jwt
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # allow unauthenticated users to access the login and token refresh routes
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/token/refresh, roles: PUBLIC_ACCESS }
        # but require authentication for all other admin routes
        - { path: ^/, roles: ROLE_USER }