api_login_check:
    path: /login_check

#https://github.com/markitosgv/JWTRefreshTokenBundle#step-3-configure-your-own-routing-to-refresh-token
gesdinet_jwt_refresh_token:
    path: /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh